name: Mark stale pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'Stale pull request message'
          stale-pr-label: 'stale'
          days-before-pr-close: 7
          close-pr-message: 'Rejected as stale'
          only-issue-labels: 'bug'
          days-before-issue-close: 31
